# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import video_stream_pb2 as video__stream__pb2


class VideoStreamStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetVideoList = channel.unary_stream(
                '/video_stream.VideoStream/GetVideoList',
                request_serializer=video__stream__pb2.VideoListRequest.SerializeToString,
                response_deserializer=video__stream__pb2.Video.FromString,
                )
        self.StreamVideo = channel.unary_unary(
                '/video_stream.VideoStream/StreamVideo',
                request_serializer=video__stream__pb2.VideoRequest.SerializeToString,
                response_deserializer=video__stream__pb2.VideoUrl.FromString,
                )


class VideoStreamServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetVideoList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamVideo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VideoStreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetVideoList': grpc.unary_stream_rpc_method_handler(
                    servicer.GetVideoList,
                    request_deserializer=video__stream__pb2.VideoListRequest.FromString,
                    response_serializer=video__stream__pb2.Video.SerializeToString,
            ),
            'StreamVideo': grpc.unary_unary_rpc_method_handler(
                    servicer.StreamVideo,
                    request_deserializer=video__stream__pb2.VideoRequest.FromString,
                    response_serializer=video__stream__pb2.VideoUrl.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'video_stream.VideoStream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VideoStream(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetVideoList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/video_stream.VideoStream/GetVideoList',
            video__stream__pb2.VideoListRequest.SerializeToString,
            video__stream__pb2.Video.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/video_stream.VideoStream/StreamVideo',
            video__stream__pb2.VideoRequest.SerializeToString,
            video__stream__pb2.VideoUrl.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
